import { NetworkEntity, GraphEdge, PersonEntity, OrganizationEntity } from '../types/network';

export const ROOT_USER_ID = 'user-root';

export const INITIAL_ENTITIES: NetworkEntity[] = [
  // ROOT USER
  {
    id: ROOT_USER_ID,
    type: 'PERSON',
    name: 'You (Alex)',
    headline: 'Founder & Tech Operator',
    isUserRoot: true,
    identifiers: {
      emails: ['alex.user@gahiz.network'],
      phones: ['+1 555-019-2831'],
    },
    tags: ['Tech', 'Product', 'Founder'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  // ORGANIZATIONS
  {
    id: 'org-vodafone',
    type: 'ORGANIZATION',
    name: 'Vodafone Telecom',
    industry: 'Telecommunications',
    domain: 'vodafone.com',
    headquarters: 'London / Cairo',
    identifiers: { domain: 'vodafone.com' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  {
    id: 'org-fourseasons',
    type: 'ORGANIZATION',
    name: 'Four Seasons Luxury Resorts',
    industry: 'Hospitality & Luxury Hotels',
    domain: 'fourseasons.com',
    headquarters: 'Toronto / Dubai',
    identifiers: { domain: 'fourseasons.com' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  {
    id: 'org-hilton',
    type: 'ORGANIZATION',
    name: 'Hilton Worldwide',
    industry: 'Hospitality',
    domain: 'hilton.com',
    headquarters: 'McLean, Virginia',
    identifiers: { domain: 'hilton.com' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  {
    id: 'org-stripe',
    type: 'ORGANIZATION',
    name: 'Stripe',
    industry: 'Financial Infrastructure / Tech',
    domain: 'stripe.com',
    headquarters: 'San Francisco / Dublin',
    identifiers: { domain: 'stripe.com' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  {
    id: 'org-google',
    type: 'ORGANIZATION',
    name: 'Google Cloud',
    industry: 'Cloud Computing / Enterprise AI',
    domain: 'google.com',
    headquarters: 'Mountain View, California',
    identifiers: { domain: 'google.com' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  {
    id: 'org-aramco',
    type: 'ORGANIZATION',
    name: 'Saudi Aramco Ventures',
    industry: 'Energy & Venture Capital',
    domain: 'aramco.com',
    headquarters: 'Dhahran',
    identifiers: { domain: 'aramco.com' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  {
    id: 'org-tech-summit',
    type: 'ORGANIZATION',
    name: 'Global Tech & Hospitality Summit',
    industry: 'Conferences & Events',
    domain: 'techsummit.global',
    headquarters: 'Dubai',
    identifiers: { domain: 'techsummit.global' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as OrganizationEntity,

  // 1ST DEGREE (Direct contacts in phone/vCard)
  {
    id: 'person-ahmed',
    type: 'PERSON',
    name: 'Ahmed Mansour',
    headline: 'VP of Digital Strategy at Vodafone (Ex-Telecom & Hospitality Board)',
    currentRole: 'VP of Digital Strategy',
    currentOrgId: 'org-vodafone',
    pastOrgIds: ['org-google'],
    location: 'Dubai / London',
    tags: ['Close Colleague', 'Executive', 'Telecom', 'Hospitality Board'],
    identifiers: {
      emails: ['ahmed.m@vodafone.com'],
      phones: ['+971 50 123 4567'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  {
    id: 'person-sarah',
    type: 'PERSON',
    name: 'Sarah Chen',
    headline: 'Staff Technical Recruiter at Stripe',
    currentRole: 'Staff Recruiter (Engineering & Product Leadership)',
    currentOrgId: 'org-stripe',
    pastOrgIds: ['org-google'],
    location: 'San Francisco, CA',
    tags: ['University Alumni', 'Tech Recruiting', 'Hiring'],
    identifiers: {
      emails: ['schen@stripe.com'],
      phones: ['+1 415-555-8921'],
      linkedInHandle: 'sarahchen-recruiting',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  {
    id: 'person-laila',
    type: 'PERSON',
    name: 'Laila Al-Sayed',
    headline: 'Executive Events Director & VIP Protocol Lead',
    currentRole: 'Managing Director',
    currentOrgId: 'org-tech-summit',
    location: 'Riyadh / Dubai',
    tags: ['Events', 'VIP Protocol', 'Hospitality Connections'],
    identifiers: {
      emails: ['laila@techsummit.global'],
      phones: ['+966 54 888 1234'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  {
    id: 'person-david',
    type: 'PERSON',
    name: 'David Miller',
    headline: 'Principal Engineer at Google Cloud',
    currentRole: 'Principal Cloud Architect',
    currentOrgId: 'org-google',
    location: 'Seattle, WA',
    tags: ['Tech', 'Former Manager', 'Cloud'],
    identifiers: {
      emails: ['dmiller@google.com'],
      phones: ['+1 206-555-3412'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  // 2ND DEGREE (Connected to Ahmed, Sarah, Laila, David)
  {
    id: 'person-tarek',
    type: 'PERSON',
    name: 'Tarek El-Gammal',
    headline: 'Regional Director of Corporate Partnerships at Hilton Worldwide',
    currentRole: 'Regional Director of Corporate Partnerships',
    currentOrgId: 'org-hilton',
    pastOrgIds: ['org-vodafone'],
    location: 'Dubai / Cairo',
    tags: ['Hospitality VIP', 'Hotel Partnerships', 'Corporate Discounts'],
    identifiers: {
      emails: ['tarek.elgammal@hilton.com'],
      linkedInHandle: 'tarekelgammal',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  {
    id: 'person-marcus',
    type: 'PERSON',
    name: 'Marcus Vance',
    headline: 'Engineering Director & Hiring Manager for Core Payments at Stripe',
    currentRole: 'Director of Engineering (Payments Infrastructure)',
    currentOrgId: 'org-stripe',
    location: 'New York, NY',
    tags: ['Hiring Manager', 'Payments', 'Engineering Leadership'],
    identifiers: {
      emails: ['mvance@stripe.com'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  {
    id: 'person-nadia',
    type: 'PERSON',
    name: 'Nadia Rostom',
    headline: 'General Manager at Four Seasons Luxury Resort & Presidential Suites',
    currentRole: 'General Manager & Vice President of Luxury Hospitality',
    currentOrgId: 'org-fourseasons',
    pastOrgIds: ['org-hilton'],
    location: 'Dubai Jumeirah / Sharm El Sheikh',
    tags: ['VIP Hotel Access', 'GM Four Seasons', 'Discounts & Upgrades'],
    identifiers: {
      emails: ['nadia.rostom@fourseasons.com'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  {
    id: 'person-khalid',
    type: 'PERSON',
    name: 'Dr. Khalid Al-Faisal',
    headline: 'Managing Director at Saudi Aramco Energy Ventures',
    currentRole: 'Managing Director & Strategic Allocator',
    currentOrgId: 'org-aramco',
    location: 'Riyadh',
    tags: ['Venture Capital', 'Energy', 'Sovereign Wealth'],
    identifiers: {
      emails: ['khalid.faisal@aramco.com'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,

  // 3RD DEGREE
  {
    id: 'person-julian',
    type: 'PERSON',
    name: 'Julian Thorne',
    headline: 'Chief Revenue & Booking Officer at Four Seasons Global Executive Committee',
    currentRole: 'Global VP of Revenue & Member Experience',
    currentOrgId: 'org-fourseasons',
    location: 'London / Geneva',
    tags: ['Global Decision Maker', 'Executive Suites', 'Private VIP Rates'],
    identifiers: {
      emails: ['julian.t@fourseasons.com'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  } as PersonEntity,
];

export const INITIAL_EDGES: GraphEdge[] = [
  // ROOT -> 1ST DEGREE
  {
    id: 'edge-user-ahmed',
    sourceId: ROOT_USER_ID,
    targetId: 'person-ahmed',
    relationshipType: 'WORKED_WITH',
    status: 'CONFIRMED',
    strengthScore: 0.92,
    trustScore: 0.88,
    recencyTimestamp: '2025-11-10T10:00:00Z',
    notes: 'You worked closely with Ahmed at Vodafone for 3 years; frequent WhatsApp check-ins.',
    evidence: [
      {
        id: 'ev-1',
        sourceType: 'GOOGLE_CONTACTS',
        rawSnippet: 'Frequent contact (38 interactions last 12 months)',
        timestamp: '2025-12-01T00:00:00Z',
        confidenceWeight: 0.95,
      },
    ],
  },
  {
    id: 'edge-user-sarah',
    sourceId: ROOT_USER_ID,
    targetId: 'person-sarah',
    relationshipType: 'STUDIED_WITH',
    status: 'CONFIRMED',
    strengthScore: 0.84,
    trustScore: 0.85,
    recencyTimestamp: '2025-09-15T14:30:00Z',
    notes: 'Computer Science batchmates, mutually endorsed each other on LinkedIn.',
    evidence: [
      {
        id: 'ev-2',
        sourceType: 'IMPORT_VCARD',
        rawSnippet: 'University Alumni group interaction',
        timestamp: '2025-09-15T00:00:00Z',
        confidenceWeight: 0.88,
      },
    ],
  },
  {
    id: 'edge-user-laila',
    sourceId: ROOT_USER_ID,
    targetId: 'person-laila',
    relationshipType: 'KNOWS',
    status: 'CONFIRMED',
    strengthScore: 0.76,
    trustScore: 0.78,
    recencyTimestamp: '2025-08-20T18:00:00Z',
    notes: 'Met at Dubai Tech Summit 2024; connected on messaging.',
    evidence: [
      {
        id: 'ev-3',
        sourceType: 'IMPORT_VCARD',
        rawSnippet: 'Conference Contact Card',
        timestamp: '2025-08-20T00:00:00Z',
        confidenceWeight: 0.8,
      },
    ],
  },
  {
    id: 'edge-user-david',
    sourceId: ROOT_USER_ID,
    targetId: 'person-david',
    relationshipType: 'FORMER_COLLEAGUE',
    status: 'CONFIRMED',
    strengthScore: 0.8,
    trustScore: 0.82,
    recencyTimestamp: '2025-06-10T12:00:00Z',
    notes: 'Former tech lead at Google Cloud.',
    evidence: [
      {
        id: 'ev-4',
        sourceType: 'LINKEDIN_EXPORT',
        rawSnippet: 'Connected 4 years ago, shared 12 mutual colleagues',
        timestamp: '2025-06-10T00:00:00Z',
        confidenceWeight: 0.85,
      },
    ],
  },

  // 1ST DEGREE -> ORGANIZATIONS
  {
    id: 'edge-ahmed-vodafone',
    sourceId: 'person-ahmed',
    targetId: 'org-vodafone',
    relationshipType: 'WORKS_AT',
    status: 'CONFIRMED',
    strengthScore: 0.95,
    trustScore: 0.9,
    recencyTimestamp: '2026-01-01T00:00:00Z',
    evidence: [
      {
        id: 'ev-5',
        sourceType: 'PUBLIC_DIRECTORY',
        rawSnippet: 'Official Corporate Executive Registry',
        timestamp: '2026-01-01T00:00:00Z',
        confidenceWeight: 0.99,
      },
    ],
  },
  {
    id: 'edge-sarah-stripe',
    sourceId: 'person-sarah',
    targetId: 'org-stripe',
    relationshipType: 'WORKS_AT',
    status: 'CONFIRMED',
    strengthScore: 0.96,
    trustScore: 0.92,
    recencyTimestamp: '2026-01-01T00:00:00Z',
    evidence: [
      {
        id: 'ev-6',
        sourceType: 'LINKEDIN_EXPORT',
        rawSnippet: 'Current Staff Recruiter at Stripe',
        timestamp: '2026-01-01T00:00:00Z',
        confidenceWeight: 0.98,
      },
    ],
  },

  // 1ST DEGREE -> 2ND DEGREE
  {
    id: 'edge-ahmed-tarek',
    sourceId: 'person-ahmed',
    targetId: 'person-tarek',
    relationshipType: 'FORMER_COLLEAGUE',
    status: 'CONFIRMED',
    strengthScore: 0.88,
    trustScore: 0.86,
    recencyTimestamp: '2025-10-05T09:00:00Z',
    notes: 'Ahmed and Tarek co-led the Vodafone Enterprise Travel & Hospitality Corporate Deal.',
    evidence: [
      {
        id: 'ev-7',
        sourceType: 'INFERRED_OVERLAP',
        rawSnippet: 'Joint press release & co-authored corporate agreement (Vodafone x Hilton)',
        timestamp: '2025-10-05T00:00:00Z',
        confidenceWeight: 0.92,
      },
    ],
  },
  {
    id: 'edge-sarah-marcus',
    sourceId: 'person-sarah',
    targetId: 'person-marcus',
    relationshipType: 'WORKED_WITH',
    status: 'CONFIRMED',
    strengthScore: 0.93,
    trustScore: 0.91,
    recencyTimestamp: '2026-02-01T15:00:00Z',
    notes: 'Sarah is the dedicated recruiter partnering directly with Marcus to build his Payments team.',
    evidence: [
      {
        id: 'ev-8',
        sourceType: 'INFERRED_OVERLAP',
        rawSnippet: 'Active hiring manager & recruiter tandem on Stripe Engineering pipeline',
        timestamp: '2026-02-01T00:00:00Z',
        confidenceWeight: 0.96,
      },
    ],
  },
  {
    id: 'edge-laila-nadia',
    sourceId: 'person-laila',
    targetId: 'person-nadia',
    relationshipType: 'PARTNER_WITH',
    status: 'CONFIRMED',
    strengthScore: 0.87,
    trustScore: 0.84,
    recencyTimestamp: '2025-11-20T16:00:00Z',
    notes: 'Laila hosts VIP conference speakers and delegations exclusively at Nadia’s Four Seasons property.',
    evidence: [
      {
        id: 'ev-9',
        sourceType: 'PUBLIC_DIRECTORY',
        rawSnippet: 'Official Venue Host Agreement for Global Tech & Hospitality Summit',
        timestamp: '2025-11-20T00:00:00Z',
        confidenceWeight: 0.9,
      },
    ],
  },

  // 2ND DEGREE -> 3RD DEGREE & HOTEL CONNECTIONS
  {
    id: 'edge-tarek-nadia',
    sourceId: 'person-tarek',
    targetId: 'person-nadia',
    relationshipType: 'FORMER_COLLEAGUE',
    status: 'INFERRED',
    strengthScore: 0.79,
    trustScore: 0.75,
    recencyTimestamp: '2025-04-12T00:00:00Z',
    notes: 'Tarek and Nadia both served as Regional Directors in Luxury Hospitality Council.',
    evidence: [
      {
        id: 'ev-10',
        sourceType: 'INFERRED_OVERLAP',
        rawSnippet: 'Middle East Hotel Industry Board Members (2022-2024)',
        timestamp: '2025-04-12T00:00:00Z',
        confidenceWeight: 0.78,
      },
    ],
  },
  {
    id: 'edge-nadia-fourseasons',
    sourceId: 'person-nadia',
    targetId: 'org-fourseasons',
    relationshipType: 'WORKS_AT',
    status: 'CONFIRMED',
    strengthScore: 0.98,
    trustScore: 0.95,
    recencyTimestamp: '2026-01-01T00:00:00Z',
    evidence: [
      {
        id: 'ev-11',
        sourceType: 'PUBLIC_DIRECTORY',
        rawSnippet: 'Four Seasons Resort General Manager Announcement',
        timestamp: '2026-01-01T00:00:00Z',
        confidenceWeight: 0.99,
      },
    ],
  },
  {
    id: 'edge-nadia-julian',
    sourceId: 'person-nadia',
    targetId: 'person-julian',
    relationshipType: 'WORKS_AT',
    status: 'CONFIRMED',
    strengthScore: 0.85,
    trustScore: 0.82,
    recencyTimestamp: '2025-12-15T00:00:00Z',
    notes: 'Nadia reports to the Global Executive Committee chaired by Julian Thorne.',
    evidence: [
      {
        id: 'ev-12',
        sourceType: 'INFERRED_OVERLAP',
        rawSnippet: 'Internal Four Seasons Leadership Matrix',
        timestamp: '2025-12-15T00:00:00Z',
        confidenceWeight: 0.88,
      },
    ],
  },
  {
    id: 'edge-david-khalid',
    sourceId: 'person-david',
    targetId: 'person-khalid',
    relationshipType: 'PARTNER_WITH',
    status: 'INFERRED',
    strengthScore: 0.72,
    trustScore: 0.68,
    recencyTimestamp: '2025-07-22T00:00:00Z',
    notes: 'David led the Google Cloud & Aramco AI Innovation Labs initiative.',
    evidence: [
      {
        id: 'ev-13',
        sourceType: 'INFERRED_OVERLAP',
        rawSnippet: 'Joint Enterprise AI Cloud Partnership',
        timestamp: '2025-07-22T00:00:00Z',
        confidenceWeight: 0.75,
      },
    ],
  },
];
